### ISSUE TITLE
npm start gives error

### ISSUE THREAD

**Issue by royalgiant** [mewben/go-react-project#2]
Getting an error here, how do I fix it?
`
> go-react-project@0.3.0 start /Users/donaldlee/Developer/golang/src/github.com/royalgiant/dancingnomads
> gulp

[20:59:16] Requiring external module babel-register
[20:59:16] Using gulpfile ~/Developer/golang/src/github.com/royalgiant/dancingnomads/gulpfile.babel.js
[20:59:17] Starting 'client:serve'...
[20:59:17] Starting 'server:build'...
[20:59:17] Finished 'server:build' after 146 ms
[20:59:17] Starting 'server:spawn'...
[20:59:17] Finished 'server:spawn' after 3.13 ms
[20:59:17] Starting 'server:watch'...
[20:59:20] Finished 'server:watch' after 3.02 s
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn dancingnomads ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! go-react-project@0.3.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the go-react-project@0.3.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the go-react-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs go-react-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls go-react-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/donaldlee/.npm/_logs/2017-02-10T02_59_20_647Z-debug.log

`

**Comment by royalgiant** [comment]
Seems to be failing on gulp?
